app = "ollama-web-scraper"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  # GROQ_API_KEY will be set via flyctl secrets set command

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "1m"
    restart_limit = 0

# Health check for the application
[[services.http_checks]]
  interval = "10s"
  timeout = "5s"
  grace_period = "1m"
  method = "GET"
  path = "/docs"
  protocol = "http"
  restart_limit = 0